#include "thememanager.h"
#include "qapplication.h"

ThemeManager::ThemeManager(QObject *parent)
    : QObject(parent), curr_theme(Theme::LIGHT) {}

void ThemeManager::ApplyTheme(Theme theme)
{
    curr_theme = theme;
    QString style = (theme == Theme::DARK) ? DarkTheme() : LightTheme();
    qApp->setStyleSheet(style);
}

QString ThemeManager::GetCurrentThemeString() const
{
    return curr_theme == Theme::DARK ? "Темная" : "Светлая";
}

Theme ThemeManager::GetTheme() const
{
    return curr_theme;
}

QString ThemeManager::DarkTheme()
{
    return
        "QWidget {"
        "   background-color: #333333;"
        "   color: #eeeeee;"
        "}"
        "QTabWidget {"
        "   background-color: #333333;"
        "}"
        "QTabWidget::pane {"
        "   border: 1px solid #555555;"
        "   margin-top: -1px;"
        "   background: #333333;"
        "}"
        "QTabBar::tab {"
        "   background: #444444;"
        "   color: #ffffff;"
        "   padding: 8px;"
        "   border: 1px solid #555555;"
        "   border-bottom: none;"
        "   border-top-left-radius: 4px;"
        "   border-top-right-radius: 4px;"
        "}"
        "QTabBar::tab:selected {"
        "   background: #333333;"
        "   border-bottom: 2px solid #0078d7;"
        "}"
        "QTabBar::tab:disabled {"
        "   background: #2a2a2a;"
        "   color: #777777;"
        "   border-color: #444444;"
        "}"
        "QGroupBox {"
        "   border: 1px solid #555555;"
        "   margin-top: 20px;"
        "}"
        "QGroupBox::title {"
        "   subcontrol-origin: margin;"
        "   left: 10px;"
        "   color: #eeeeee;"
        "}"
        "QGroupBox:disabled {"
        "   color: #777777;"
        "   border-color: #444444;"
        "}"
        "QPushButton {"
        "   background-color: #555555;"
        "   border: 1px solid #666666;"
        "   padding: 5px;"
        "}"
        "QPushButton:hover {"
        "   background-color: #666666;"
        "}"
        "QPushButton:disabled {"
        "   background-color: #3a3a3a;"
        "   color: #777777;"
        "   border-color: #4a4a4a;"
        "}"
        "QComboBox, QSpinBox {"
        "   background-color: #444444;"
        "   border: 1px solid #555555;"
        "   color: #ffffff;"
        "}"
        "QComboBox:disabled, QSpinBox:disabled {"
        "   background-color: #3a3a3a;"
        "   color: #777777;"
        "   border-color: #4a4a4a;"
        "}"
        "QLabel {"
        "   color: #eeeeee;"
        "}"
        "QLabel:disabled {"
        "   color: #777777;"
        "}";
}

QString ThemeManager::LightTheme()
{
    return
        "QWidget {"
        "   background-color: #f0f0f0;"
        "   color: #333333;"
        "}"
        "QTabWidget {"
        "   background-color: #f0f0f0;"
        "}"
        "QTabWidget::pane {"
        "   border: 1px solid #cccccc;"
        "   margin-top: -1px;"
        "   background: #f0f0f0;"
        "}"
        "QTabBar::tab {"
        "   background: #e0e0e0;"
        "   color: #333333;"
        "   padding: 8px;"
        "   border: 1px solid #cccccc;"
        "   border-bottom: none;"
        "   border-top-left-radius: 4px;"
        "   border-top-right-radius: 4px;"
        "}"
        "QTabBar::tab:selected {"
        "   background: #f0f0f0;"
        "   border-bottom: 2px solid #0078d7;"
        "}"
        "QTabBar::tab:disabled {"
        "   background: #d0d0d0;"
        "   color: #999999;"
        "   border-color: #bbbbbb;"
        "}"
        "QGroupBox {"
        "   border: 1px solid #cccccc;"
        "   margin-top: 20px;"
        "}"
        "QGroupBox::title {"
        "   subcontrol-origin: margin;"
        "   left: 10px;"
        "   color: #333333;"
        "}"
        "QGroupBox:disabled {"
        "   color: #999999;"
        "   border-color: #bbbbbb;"
        "}"
        "QPushButton {"
        "   background-color: #e0e0e0;"
        "   border: 1px solid #cccccc;"
        "   padding: 5px;"
        "}"
        "QPushButton:hover {"
        "   background-color: #d0d0d0;"
        "}"
        "QPushButton:disabled {"
        "   background-color: #e8e8e8;"
        "   color: #999999;"
        "   border-color: #cccccc;"
        "}"
        "QComboBox, QSpinBox {"
        "   background-color: #ffffff;"
        "   border: 1px solid #cccccc;"
        "   color: #333333;"
        "}"
        "QComboBox:disabled, QSpinBox:disabled {"
        "   background-color: #f5f5f5;"
        "   color: #999999;"
        "   border-color: #dddddd;"
        "}"
        "QLabel {"
        "   color: #333333;"
        "}"
        "QLabel:disabled {"
        "   color: #999999;"
        "}";
}
